# AppVeyor configuration based on https://github.com/AMOS-ss16-proj3/amos-ss16-proj3/blob/master/appveyor.yml

clone_folder: c:\projects\sap

environment:
  CYG_ROOT: C:\cygwin64

install:
  - cinst winflexbison
  - refreshenv

platform:
  - x64

configuration:
  - RelWithDebInfo

matrix:
  fast_finish: true

before_build:
  - ps: .\tools\windows-provision-source.ps1

build_script:
  - ps: .\tools\windows-build-source.ps1

after_build:
  - copy c:\projects\sap\build\run\%Configuration%\plugins\sap.dll c:\projects\sap\build\sap-v0.4.1-dev.dll

artifacts:
  - path: "build\\*.dll"
