# AppVeyor configuration based on https://github.com/AMOS-ss16-proj3/amos-ss16-proj3/blob/master/appveyor.yml

clone_folder: c:\projects\sap

environment:
  CYG_ROOT: C:\cygwin64

install:
  - cinst winflexbison
  - refreshenv

platform:
  - x64

before_build:
  # add Cygwin to PATH
  - set PATH=%PATH%;C:\cygwin64\bin\
  - set PATH=C:\cygwin64\bin\;%PATH%
  # get Wireshark and checkout the branch
  - mkdir c:\projects\wireshark
  - cd C:\projects\wireshark
  - git init
  - git remote add -t master-2.2 -f origin https://github.com/wireshark/wireshark
  - git checkout master-2.2
  # set necessary environment variables:
  - cmd: set CYGWIN=nodosfilewarning
  - cmd: set WIRESHARK_BASE_DIR=c:\projects
  - cmd: set WIRESHARK_TARGET_PLATFORM=win64
  - cmd: set QT5_BASE_DIR=c:\Qt\5.6\msvc2013
  # insert our plugin files to wireshark
  - cmd: xcopy /E c:\projects\sap\ plugins\
  # run the adjustment scripts
  - bash patch plugins/sap/wireshark-master-2.2.patch
  - ps: Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile c:\projects\cygwin-setup.exe
  - mkdir c:\projects\cyg-packages
  - c:\projects\cygwin-setup.exe -q -n -N -d -R C:\cygwin64 -s http://ftp.hawo.stw.uni-erlangen.de/cygwin/ -l c:\projects\cyg-packages -P flex -P bison
  - cmd: set WIRESHARK_CYGWIN_INSTALL_PATH=C:\cygwin64

build_script:
  - mkdir c:\projects\wireshark-build
  - cd  c:\projects\wireshark-build
  - cmake -DENABLE_CHM_GUIDES=on -G "Visual Studio 12 Win64" c:\projects\wireshark
  - msbuild /m /p:Configuration=RelWithDebInfo c:\projects\wireshark-build\plugins\sap\sap.vcxproj

after_test:
  - cp c:\projects\wireshark-build\run\RelWithDebInfo\plugins\sap.dll c:\projects\sap_build$env:appveyor_build_number.dll

artifacts:
  - path: c:\projects\sap_build$env:appveyor_build_number.dll
