# AppVeyor configuration based on https://github.com/AMOS-ss16-proj3/amos-ss16-proj3/blob/master/appveyor.yml

clone_folder: c:\projects\sap

environment:
  CYG_ROOT: C:\cygwin64

install:
  - cinst winflexbison
  - refreshenv

platform:
  - x64

before_build:
  - ps: .\tools\windows-provision-source.ps1

build_script:
<<<<<<< HEAD
  - ps: .\tools\windows-build-source.ps1

after_build:
  - copy c:\projects\sap\build\run\%Configuration%\plugins\sap.dll c:\projects\sap\build\sap-v0.4.1-dev.dll
=======
  - mkdir c:\projects\sap\build
  - cd c:\projects\sap\build
  - cmake -DENABLE_CHM_GUIDES=on -G "Visual Studio 12 Win64" c:\projects\wireshark
  - msbuild /m /p:Configuration=RelWithDebInfo plugins\sap\sap.vcxproj
>>>>>>> parent of 4b35a66... Using configuration variable

artifacts:
  - path: "build\\run\\RelWithDebInfo\\plugins\\sap.dll"
