language: cpp

compiler:
  - clang
  - gcc

env:
  - WIRESHARK_BRANCH=master-1.12
  - WIRESHARK_BRANCH=master-2.0
  - BUILD_STANDALONE=no
  - BUILD_STANDALONE=yes

# Since Wireshark's ppa only have stable version, we can't test standalone against 1.12 
matrix:
  exclude:
    - env: WIRESHARK_BRANCH=master-1.12 BUILD_STANDALONE=yes


before_install:
  - if [ ${BUILD_STANDALONE} == "yes" ]; then sudo sudo add-apt-repository ppa:wireshark-dev/stable -y; fi

  - sudo apt-get update -qq

  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        sudo apt-get install wireshark wireshark-dev tshark -qq;
    fi

  - if [ ${BUILD_STANDALONE} == "no" ]; then
      sudo apt-get install libglib2.0-dev libpcap-dev flex bison make qt-sdk libgtk-3-dev -qq;
      sudo apt-get build-dep wireshark -qq;
      mkdir ${HOME}/wireshark-$WIRESHARK_BRANCH;
      cd ${HOME}/wireshark-$WIRESHARK_BRANCH;
      git init;
      git remote add -t $WIRESHARK_BRANCH -f origin https://github.com/wireshark/wireshark;
      git checkout $WIRESHARK_BRANCH;
      mkdir plugins/sap;
      cp -R $TRAVIS_BUILD_DIR/* plugins/sap/;
      git apply $TRAVIS_BUILD_DIR/wireshark.patch;
    fi

  - sudo apt-get install libxml2-dev libxslt-dev python-dev -qq
  - sudo -H pip install pysap pyshark

install:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
      ./autogen.sh && ./configure --disable-wireshark --disable-editcap --disable-captype -disable-capinfos --disable-mergecap --disable-dumpcap --disable-reordercap --disable-text2pcap --disable-randpkt --disable-dftest --disable-rawshark && make;
    fi

  - if [ ${BUILD_STANDALONE} == "yes" ]; then
      cmake . && make && make install;
    fi

script: 
  - if [ ${BUILD_STANDALONE} == "no" ]; then
      python ${HOME}/wireshark-$WIRESHARK_BRANCH/plugins/sap/tests/__init__.py;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
      python ${TRAVIS_BUILD_DIR}/tests/__init__.py;
    fi

