language: cpp

compiler:
  - clang
  - gcc

env:
  - WIRESHARK_BRANCH=master-2.0 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=no
  # Stand alone build is disabled by now, as the wireshark-dev PPA is on the
  # Wireshark 2.2 branch and the plugin is in the 2.0 one.
  #- WIRESHARK_BRANCH=master-2.0 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=yes

before_install:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        $PLUGIN_DIR/tools/ubuntu-provision-source.sh;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        $PLUGIN_DIR/tools/ubuntu-provision-standalone.sh;
    fi

install:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        $PLUGIN_DIR/tools/ubuntu-build-source.sh;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        $PLUGIN_DIR/tools/ubuntu-build-standalone.sh;
    fi

script:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
      python ${HOME}/wireshark-$WIRESHARK_BRANCH/plugins/sap/tests/__init__.py;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
      python ${TRAVIS_BUILD_DIR}/tests/__init__.py;
    fi
