language: cpp

dist: trusty
sudo: required

compiler:
  - clang
  - gcc

env:
  - WIRESHARK_BRANCH=master-2.2 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=no
  - WIRESHARK_BRANCH=master-2.2 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=yes

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/5326
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

  - if [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-source.sh;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-standalone.sh;
    fi

install:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-source.sh;
        export PATH=${PATH}:${HOME}/wireshark-${WIRESHARK_BRANCH}/build/run;
        export WIRESHARK_RUN_FROM_BUILD_DIRECTORY=1;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-standalone.sh;
    fi

script:
  - python ${PLUGIN_DIR}/tests/__init__.py

before_deploy:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        cp build/run/plugins/sap.so build/sap-${TRAVIS_TAG}-linux-x64.so
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        cp build/sap.so build/sap-${TRAVIS_TAG}-linux-x64.so
    fi

deploy:
    provider: releases
    api_key:
        secure: "HmUIZ6L/W2Njxnm8z1xWrtka1cxzQRZo62asHljFXYj9QCMBmCDGr3CHvJW42D9c8dV3Q7f2HOO0WEatDo+1IWtoZZtuQ8Jbxhz5cegobhuO5Wj7q+45DPf31/dILufDG9Sy2vmgJV0EWxuvYJXMelxjd8+yfXCtGLrZbpcWUPU="
    file: "build/*.so"
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
        repo: CoreSecurity/SAP-Dissection-plug-in-for-Wireshark
        condition: "${BUILD_STANDALONE} == \"yes\""
