language: cpp

dist: trusty
sudo: required

compiler:
  - clang
  - gcc

env:
  - WIRESHARK_BRANCH=master-2.2 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=no
  - WIRESHARK_BRANCH=master-2.2 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=yes

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/5326
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

  - if [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-source.sh;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-standalone.sh;
    fi

install:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-source.sh;
        export PATH=${PATH}:${HOME}/wireshark-${WIRESHARK_BRANCH}/build/run;
        export WIRESHARK_RUN_FROM_BUILD_DIRECTORY=1;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-standalone.sh;
    fi

script:
  - python ${PLUGIN_DIR}/tests/__init__.py

before_deploy:
  - cp /home/travis/.wireshark/plugins/sap.so ${PLUGIN_DIR}/sap-${TRAVIS_TAG}_linux_x86-64.so
